stages:
  clean:
    cmd: uv run src/clean.py data/raw/events.csv data/clean/events.csv
    deps:
    - data/raw/events.csv
    - src/clean.py
    outs:
    - data/clean/events.csv
  transform:
    cmd: uv run src/transform.py data/clean/events.csv 
      data/transformed/events.csv
    deps:
    - data/clean/events.csv
    - src/transform.py
    outs:
    - data/transformed/events.csv
  featurize:
    cmd: uv run src/featurize.py data/transformed/events.csv 
      data/features/events.csv
    deps:
    - data/transformed/events.csv
    - src/featurize.py
    outs:
    - data/features/events.csv
